package models

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

type Tool struct {
	Definition mcp.Tool
	Handler    func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error)
}

// ListChangedBlocksRequest represents the ListChangedBlocksRequest schema from the OpenAPI specification
type ListChangedBlocksRequest struct {
}

// CompleteSnapshotResponse represents the CompleteSnapshotResponse schema from the OpenAPI specification
type CompleteSnapshotResponse struct {
	Status interface{} `json:"Status,omitempty"` // The status of the snapshot.
}

// CompleteSnapshotRequest represents the CompleteSnapshotRequest schema from the OpenAPI specification
type CompleteSnapshotRequest struct {
}

// StartSnapshotrequest represents the StartSnapshotrequest schema from the OpenAPI specification
type StartSnapshotrequest struct {
	Volumesize int `json:"VolumeSize"` // The size of the volume, in GiB. The maximum size is <code>65536</code> GiB (64 TiB).
	Clienttoken string `json:"ClientToken,omitempty"` // <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully. The subsequent retries with the same client token return the result from the original successful request and they have no additional effect.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-direct-api-idempotency.html"> Idempotency for StartSnapshot API</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
	Description string `json:"Description,omitempty"` // A description for the snapshot.
	Encrypted bool `json:"Encrypted,omitempty"` // <p>Indicates whether to encrypt the snapshot.</p> <p>You can't specify <b>Encrypted</b> and <b> ParentSnapshotId</b> in the same request. If you specify both parameters, the request fails with <code>ValidationException</code>.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>To create an encrypted snapshot, you must have permission to use the KMS key. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>
	Kmskeyarn string `json:"KmsKeyArn,omitempty"` // <p>The Amazon Resource Name (ARN) of the Key Management Service (KMS) key to be used to encrypt the snapshot.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>To create an encrypted snapshot, you must have permission to use the KMS key. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>
	Parentsnapshotid string `json:"ParentSnapshotId,omitempty"` // <p>The ID of the parent snapshot. If there is no parent snapshot, or if you are creating the first snapshot for an on-premises volume, omit this parameter.</p> <p>You can't specify <b>ParentSnapshotId</b> and <b>Encrypted</b> in the same request. If you specify both parameters, the request fails with <code>ValidationException</code>.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>If you specify an encrypted parent snapshot, you must have permission to use the KMS key that was used to encrypt the parent snapshot. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>
	Tags []Tag `json:"Tags,omitempty"` // The tags to apply to the snapshot.
	Timeout int `json:"Timeout,omitempty"` // <p>The amount of time (in minutes) after which the snapshot is automatically cancelled if:</p> <ul> <li> <p>No blocks are written to the snapshot.</p> </li> <li> <p>The snapshot is not completed after writing the last block of data.</p> </li> </ul> <p>If no value is specified, the timeout defaults to <code>60</code> minutes.</p>
}

// ChangedBlock represents the ChangedBlock schema from the OpenAPI specification
type ChangedBlock struct {
	Blockindex interface{} `json:"BlockIndex,omitempty"` // The block index.
	Firstblocktoken interface{} `json:"FirstBlockToken,omitempty"` // The block token for the block index of the <code>FirstSnapshotId</code> specified in the <code>ListChangedBlocks</code> operation. This value is absent if the first snapshot does not have the changed block that is on the second snapshot.
	Secondblocktoken interface{} `json:"SecondBlockToken,omitempty"` // The block token for the block index of the <code>SecondSnapshotId</code> specified in the <code>ListChangedBlocks</code> operation.
}

// GetSnapshotBlockResponse represents the GetSnapshotBlockResponse schema from the OpenAPI specification
type GetSnapshotBlockResponse struct {
	Blockdata interface{} `json:"BlockData,omitempty"` // The data content of the block.
}

// ListChangedBlocksResponse represents the ListChangedBlocksResponse schema from the OpenAPI specification
type ListChangedBlocksResponse struct {
	Blocksize interface{} `json:"BlockSize,omitempty"` // The size of the blocks in the snapshot, in bytes.
	Changedblocks interface{} `json:"ChangedBlocks,omitempty"` // An array of objects containing information about the changed blocks.
	Expirytime interface{} `json:"ExpiryTime,omitempty"` // The time when the <code>BlockToken</code> expires.
	Nexttoken interface{} `json:"NextToken,omitempty"` // The token to use to retrieve the next page of results. This value is null when there are no more results to return.
	Volumesize interface{} `json:"VolumeSize,omitempty"` // The size of the volume in GB.
}

// PutSnapshotBlockrequest represents the PutSnapshotBlockrequest schema from the OpenAPI specification
type PutSnapshotBlockrequest struct {
	Blockdata string `json:"BlockData"` // <p>The data to write to the block.</p> <p>The block data is not signed as part of the Signature Version 4 signing process. As a result, you must generate and provide a Base64-encoded SHA256 checksum for the block data using the <b>x-amz-Checksum</b> header. Also, you must specify the checksum algorithm using the <b>x-amz-Checksum-Algorithm</b> header. The checksum that you provide is part of the Signature Version 4 signing process. It is validated against a checksum generated by Amazon EBS to ensure the validity and authenticity of the data. If the checksums do not correspond, the request fails. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html#ebsapis-using-checksums"> Using checksums with the EBS direct APIs</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
}

// PutSnapshotBlockResponse represents the PutSnapshotBlockResponse schema from the OpenAPI specification
type PutSnapshotBlockResponse struct {
}

// GetSnapshotBlockRequest represents the GetSnapshotBlockRequest schema from the OpenAPI specification
type GetSnapshotBlockRequest struct {
}

// Tag represents the Tag schema from the OpenAPI specification
type Tag struct {
	Key interface{} `json:"Key,omitempty"` // The key of the tag.
	Value interface{} `json:"Value,omitempty"` // The value of the tag.
}

// PutSnapshotBlockRequest represents the PutSnapshotBlockRequest schema from the OpenAPI specification
type PutSnapshotBlockRequest struct {
	Blockdata interface{} `json:"BlockData"` // <p>The data to write to the block.</p> <p>The block data is not signed as part of the Signature Version 4 signing process. As a result, you must generate and provide a Base64-encoded SHA256 checksum for the block data using the <b>x-amz-Checksum</b> header. Also, you must specify the checksum algorithm using the <b>x-amz-Checksum-Algorithm</b> header. The checksum that you provide is part of the Signature Version 4 signing process. It is validated against a checksum generated by Amazon EBS to ensure the validity and authenticity of the data. If the checksums do not correspond, the request fails. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html#ebsapis-using-checksums"> Using checksums with the EBS direct APIs</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
}

// StartSnapshotRequest represents the StartSnapshotRequest schema from the OpenAPI specification
type StartSnapshotRequest struct {
	Volumesize interface{} `json:"VolumeSize"` // The size of the volume, in GiB. The maximum size is <code>65536</code> GiB (64 TiB).
	Clienttoken interface{} `json:"ClientToken,omitempty"` // <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully. The subsequent retries with the same client token return the result from the original successful request and they have no additional effect.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-direct-api-idempotency.html"> Idempotency for StartSnapshot API</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
	Description interface{} `json:"Description,omitempty"` // A description for the snapshot.
	Encrypted interface{} `json:"Encrypted,omitempty"` // <p>Indicates whether to encrypt the snapshot.</p> <p>You can't specify <b>Encrypted</b> and <b> ParentSnapshotId</b> in the same request. If you specify both parameters, the request fails with <code>ValidationException</code>.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>To create an encrypted snapshot, you must have permission to use the KMS key. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>
	Kmskeyarn interface{} `json:"KmsKeyArn,omitempty"` // <p>The Amazon Resource Name (ARN) of the Key Management Service (KMS) key to be used to encrypt the snapshot.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>To create an encrypted snapshot, you must have permission to use the KMS key. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>
	Parentsnapshotid interface{} `json:"ParentSnapshotId,omitempty"` // <p>The ID of the parent snapshot. If there is no parent snapshot, or if you are creating the first snapshot for an on-premises volume, omit this parameter.</p> <p>You can't specify <b>ParentSnapshotId</b> and <b>Encrypted</b> in the same request. If you specify both parameters, the request fails with <code>ValidationException</code>.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>If you specify an encrypted parent snapshot, you must have permission to use the KMS key that was used to encrypt the parent snapshot. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>
	Tags interface{} `json:"Tags,omitempty"` // The tags to apply to the snapshot.
	Timeout interface{} `json:"Timeout,omitempty"` // <p>The amount of time (in minutes) after which the snapshot is automatically cancelled if:</p> <ul> <li> <p>No blocks are written to the snapshot.</p> </li> <li> <p>The snapshot is not completed after writing the last block of data.</p> </li> </ul> <p>If no value is specified, the timeout defaults to <code>60</code> minutes.</p>
}

// ListSnapshotBlocksResponse represents the ListSnapshotBlocksResponse schema from the OpenAPI specification
type ListSnapshotBlocksResponse struct {
	Blocks interface{} `json:"Blocks,omitempty"` // An array of objects containing information about the blocks.
	Expirytime interface{} `json:"ExpiryTime,omitempty"` // The time when the <code>BlockToken</code> expires.
	Nexttoken interface{} `json:"NextToken,omitempty"` // The token to use to retrieve the next page of results. This value is null when there are no more results to return.
	Volumesize interface{} `json:"VolumeSize,omitempty"` // The size of the volume in GB.
	Blocksize interface{} `json:"BlockSize,omitempty"` // The size of the blocks in the snapshot, in bytes.
}

// StartSnapshotResponse represents the StartSnapshotResponse schema from the OpenAPI specification
type StartSnapshotResponse struct {
	Parentsnapshotid interface{} `json:"ParentSnapshotId,omitempty"` // The ID of the parent snapshot.
	Status interface{} `json:"Status,omitempty"` // The status of the snapshot.
	Description interface{} `json:"Description,omitempty"` // The description of the snapshot.
	Snapshotid interface{} `json:"SnapshotId,omitempty"` // The ID of the snapshot.
	Starttime interface{} `json:"StartTime,omitempty"` // The timestamp when the snapshot was created.
	Blocksize interface{} `json:"BlockSize,omitempty"` // The size of the blocks in the snapshot, in bytes.
	Kmskeyarn interface{} `json:"KmsKeyArn,omitempty"` // The Amazon Resource Name (ARN) of the Key Management Service (KMS) key used to encrypt the snapshot.
	Ownerid interface{} `json:"OwnerId,omitempty"` // The Amazon Web Services account ID of the snapshot owner.
	Tags interface{} `json:"Tags,omitempty"` // The tags applied to the snapshot. You can specify up to 50 tags per snapshot. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html"> Tagging your Amazon EC2 resources</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.
	Volumesize interface{} `json:"VolumeSize,omitempty"` // The size of the volume, in GiB.
	Ssetype interface{} `json:"SseType,omitempty"` // Reserved for future use.
}

// Block represents the Block schema from the OpenAPI specification
type Block struct {
	Blocktoken interface{} `json:"BlockToken,omitempty"` // The block token for the block index.
	Blockindex interface{} `json:"BlockIndex,omitempty"` // The block index.
}

// ListSnapshotBlocksRequest represents the ListSnapshotBlocksRequest schema from the OpenAPI specification
type ListSnapshotBlocksRequest struct {
}
