/*
 * Amazon Elastic Block Store
 * <p>You can use the Amazon Elastic Block Store (Amazon EBS) direct APIs to create Amazon EBS snapshots, write data directly to your snapshots, read data on your snapshots, and identify the differences or changes between two snapshots. If you’re an independent software vendor (ISV) who offers backup services for Amazon EBS, the EBS direct APIs make it more efficient and cost-effective to track incremental changes on your Amazon EBS volumes through snapshots. This can be done without having to create new volumes from snapshots, and then use Amazon Elastic Compute Cloud (Amazon EC2) instances to compare the differences.</p> <p>You can create incremental snapshots directly from data on-premises into volumes and the cloud to use for quick disaster recovery. With the ability to write and read snapshots, you can write your on-premises data to an snapshot during a disaster. Then after recovery, you can restore it back to Amazon Web Services or on-premises from the snapshot. You no longer need to build and maintain complex mechanisms to copy data to and from Amazon EBS.</p> <p>This API reference provides detailed information about the actions, data types, parameters, and errors of the EBS direct APIs. For more information about the elements that make up the EBS direct APIs, and examples of how to use them effectively, see <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html\">Accessing the Contents of an Amazon EBS Snapshot</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>. For more information about the supported Amazon Web Services Regions, endpoints, and service quotas for the EBS direct APIs, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/ebs-service.html\">Amazon Elastic Block Store Endpoints and Quotas</a> in the <i>Amazon Web Services General Reference</i>.</p>
 *
 * The version of the OpenAPI document: 2019-11-02
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ChangedBlock;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListChangedBlocksResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:56:00.934756+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ListChangedBlocksResponse {
  public static final String SERIALIZED_NAME_CHANGED_BLOCKS = "ChangedBlocks";
  @SerializedName(SERIALIZED_NAME_CHANGED_BLOCKS)
  @javax.annotation.Nullable
  private List<ChangedBlock> changedBlocks;

  public static final String SERIALIZED_NAME_EXPIRY_TIME = "ExpiryTime";
  @SerializedName(SERIALIZED_NAME_EXPIRY_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime expiryTime;

  public static final String SERIALIZED_NAME_VOLUME_SIZE = "VolumeSize";
  @SerializedName(SERIALIZED_NAME_VOLUME_SIZE)
  @javax.annotation.Nullable
  private Integer volumeSize;

  public static final String SERIALIZED_NAME_BLOCK_SIZE = "BlockSize";
  @SerializedName(SERIALIZED_NAME_BLOCK_SIZE)
  @javax.annotation.Nullable
  private Integer blockSize;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public ListChangedBlocksResponse() {
  }

  public ListChangedBlocksResponse changedBlocks(@javax.annotation.Nullable List<ChangedBlock> changedBlocks) {
    this.changedBlocks = changedBlocks;
    return this;
  }

  public ListChangedBlocksResponse addChangedBlocksItem(ChangedBlock changedBlocksItem) {
    if (this.changedBlocks == null) {
      this.changedBlocks = new ArrayList<>();
    }
    this.changedBlocks.add(changedBlocksItem);
    return this;
  }

  /**
   * An array of objects containing information about the changed blocks.
   * @return changedBlocks
   */
  @javax.annotation.Nullable
  public List<ChangedBlock> getChangedBlocks() {
    return changedBlocks;
  }

  public void setChangedBlocks(@javax.annotation.Nullable List<ChangedBlock> changedBlocks) {
    this.changedBlocks = changedBlocks;
  }


  public ListChangedBlocksResponse expiryTime(@javax.annotation.Nullable OffsetDateTime expiryTime) {
    this.expiryTime = expiryTime;
    return this;
  }

  /**
   * The time when the &lt;code&gt;BlockToken&lt;/code&gt; expires.
   * @return expiryTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiryTime() {
    return expiryTime;
  }

  public void setExpiryTime(@javax.annotation.Nullable OffsetDateTime expiryTime) {
    this.expiryTime = expiryTime;
  }


  public ListChangedBlocksResponse volumeSize(@javax.annotation.Nullable Integer volumeSize) {
    this.volumeSize = volumeSize;
    return this;
  }

  /**
   * The size of the volume in GB.
   * minimum: 1
   * @return volumeSize
   */
  @javax.annotation.Nullable
  public Integer getVolumeSize() {
    return volumeSize;
  }

  public void setVolumeSize(@javax.annotation.Nullable Integer volumeSize) {
    this.volumeSize = volumeSize;
  }


  public ListChangedBlocksResponse blockSize(@javax.annotation.Nullable Integer blockSize) {
    this.blockSize = blockSize;
    return this;
  }

  /**
   * The size of the blocks in the snapshot, in bytes.
   * @return blockSize
   */
  @javax.annotation.Nullable
  public Integer getBlockSize() {
    return blockSize;
  }

  public void setBlockSize(@javax.annotation.Nullable Integer blockSize) {
    this.blockSize = blockSize;
  }


  public ListChangedBlocksResponse nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListChangedBlocksResponse listChangedBlocksResponse = (ListChangedBlocksResponse) o;
    return Objects.equals(this.changedBlocks, listChangedBlocksResponse.changedBlocks) &&
        Objects.equals(this.expiryTime, listChangedBlocksResponse.expiryTime) &&
        Objects.equals(this.volumeSize, listChangedBlocksResponse.volumeSize) &&
        Objects.equals(this.blockSize, listChangedBlocksResponse.blockSize) &&
        Objects.equals(this.nextToken, listChangedBlocksResponse.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedBlocks, expiryTime, volumeSize, blockSize, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListChangedBlocksResponse {\n");
    sb.append("    changedBlocks: ").append(toIndentedString(changedBlocks)).append("\n");
    sb.append("    expiryTime: ").append(toIndentedString(expiryTime)).append("\n");
    sb.append("    volumeSize: ").append(toIndentedString(volumeSize)).append("\n");
    sb.append("    blockSize: ").append(toIndentedString(blockSize)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("ChangedBlocks", "ExpiryTime", "VolumeSize", "BlockSize", "NextToken"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListChangedBlocksResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListChangedBlocksResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListChangedBlocksResponse is not found in the empty JSON string", ListChangedBlocksResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListChangedBlocksResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListChangedBlocksResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("ChangedBlocks") != null && !jsonObj.get("ChangedBlocks").isJsonNull()) {
        JsonArray jsonArraychangedBlocks = jsonObj.getAsJsonArray("ChangedBlocks");
        if (jsonArraychangedBlocks != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ChangedBlocks").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ChangedBlocks` to be an array in the JSON string but got `%s`", jsonObj.get("ChangedBlocks").toString()));
          }

          // validate the optional field `ChangedBlocks` (array)
          for (int i = 0; i < jsonArraychangedBlocks.size(); i++) {
            ChangedBlock.validateJsonElement(jsonArraychangedBlocks.get(i));
          };
        }
      }
      if ((jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) && !jsonObj.get("NextToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NextToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NextToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListChangedBlocksResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListChangedBlocksResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListChangedBlocksResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListChangedBlocksResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ListChangedBlocksResponse>() {
           @Override
           public void write(JsonWriter out, ListChangedBlocksResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListChangedBlocksResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListChangedBlocksResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListChangedBlocksResponse
   * @throws IOException if the JSON string is invalid with respect to ListChangedBlocksResponse
   */
  public static ListChangedBlocksResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListChangedBlocksResponse.class);
  }

  /**
   * Convert an instance of ListChangedBlocksResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

